name: NotifierPlayer
description: Complete plugin to mention players like your server!
version: 1.0.4
author: RedBoard
api-version: 1.13
main: fr.redboard.notifierplayer.NotifierPlayer
commands:
  notifier:
    permissions:
      notifier.bypass:
      notifier.everyone:
      notifier.admin:
